### ISSUE TITLE
.io link 404

### ISSUE THREAD

**Issue by trashbirdecology** [EcologicalTraitData/TraitDataList#1]
_didnt poke around to see where so its up to you_

On the [.io/traitdatalist](https://ecologicaltraitdata.github.io/TraitDataList/), there is a reference to a 404 webpage:
> The ETS (https://ecologicaltraitdata.github.io/TraitDataStandard/) defines a vocabulary of essential columns for raw data of functional traits for ecological research.

**Comment by fdschneider** [comment]
Thanks Jessica. It's been fixed. However, note that this repository is just an example for a thesaurus of traits for a specific use-case and not designed for broader use in other projects.
